create Database nsj;
use nsj;
CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR (250) NOT NULL,
  password VARCHAR (250) NOT NULL
);
CREATE TABLE cases (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  suit_number VARCHAR (250) NOT NULL,
  parties VARCHAR (250) NOT NULL,
  court_room VARCHAR (250) NOT NULL,
  date VARCHAR (250) NOT NULL
);
CREATE TABLE courts (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  court_room VARCHAR (250) NOT NULL,
  judges VARCHAR (250) NOT NULL
);
CREATE TABLE news (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR (250) NOT NULL,
  content VARCHAR (250) NOT NULL,
  date VARCHAR (250) NOT NULL
);
